theme: jekyll-theme-minimal
title: VoteNov
logo: /assets/img/logo.png
description: On November 3, 2020, the citizens of the United States of America will be heard. Vote.
show_downloads: false
google_analytics: UA-115628752-1
