theme: jekyll-theme-minimal
title: Vote November
logo: /assets/VoteNov_Logo1.png
description: On November 6, 2018, the citizens of the United States of America will be heard. Vote.
show_downloads: false
google_analytics: UA-115628752-1
